import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

export async function POST(req: Request) {
  try {
    const { message } = await req.json();

    if (!message) {
      return NextResponse.json({ reply: "No message provided." }, { status: 400 });
    }

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });


    const result = await model.generateContent(message);
    const reply = result.response?.text() || "No output generated by the model.";

    return NextResponse.json({ reply });
    
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    return NextResponse.json(
      { reply: "Sorry, something went wrong.", error: error.message },
      { status: 500 }
    );
  }
}
