import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { prismaclient } from "@/lib/db";

const FREE_LIMIT = 10;
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

async function generateWithRag(
  clerkId: string,
  templatePrompt: string,
  userInput: Record<string, unknown>,
  cite: boolean
) {
  const res = await fetch(`${process.env.RAG_SERVICE_URL}/generate`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.RAG_API_KEY!,
    },
    body: JSON.stringify({
      clerk_id: clerkId, // always taken from the session, never from the client
      template_prompt: templatePrompt,
      user_input: Object.fromEntries(
        Object.entries(userInput).map(([k, v]) => [k, String(v ?? "")])
      ),
      use_knowledge: true,
      cite,
    }),
    signal: AbortSignal.timeout(60000),
  });
  if (!res.ok) throw new Error(`RAG service ${res.status}`);
  return res.json();
}

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ reply: "Unauthorized." }, { status: 401 });
    }
    const user = await prismaclient.user.findUnique({
      where: { clerkid: userId },
      select: { plan: true },
    });
    if (user?.plan !== "PRO") {
      const used = await prismaclient.aiOutput.count({ where: { clerkid: userId } });
      if (used >= FREE_LIMIT) {
        return NextResponse.json(
          { reply: "Credit limit reached. Please upgrade your plan." },
          { status: 403 }
        );
      }
    }

    const { message, templatePrompt, userInput, useKnowledge, slug } =
      await req.json();

    if (!message) {
      return NextResponse.json({ reply: "No message provided." }, { status: 400 });
    }

    if (useKnowledge && templatePrompt && userInput) {
      try {
        const data = await generateWithRag(
          userId,
          templatePrompt,
          userInput,
          slug === "blog-content-generation"
        );
        return NextResponse.json({ reply: data.reply, sources: data.sources });
      } catch (err) {
        console.error("RAG failed, falling back to plain Gemini:", err);
      }
    }

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const result = await model.generateContent(message);
    const reply = result.response?.text() || "No output generated by the model.";
    return NextResponse.json({ reply, sources: [] });
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    return NextResponse.json(
      { reply: "Sorry, something went wrong." },
      { status: 500 }
    );
  }
}