import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import SideNav from "./_components/SideNav";
import Header from "./_components/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <div className="hidden md:block md:w-64 fixed">
            <SideNav />
          </div>
          <div className="md:ml-64"><Header /></div>
          <div className="md:ml-64 bg-slate-200 min-h-screen">
              {children}
          </div>
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
